// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqkzsbirwoqcljzpbioe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxa3pzYmlyd29xY2xqenBiaW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODEzMzgsImV4cCI6MjA2NjI1NzMzOH0.OwanFtof9JI2DikYRh3NPflyvun5owNtfuVlvHsC2Y4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);